init:
	python -m venv venv-sparkify-cassandra
	source venv-sparkify-cassandra/bin/activate.sh

init_fish_shell:
	python -m venv venv-sparkify-cassandra
	source venv-sparkify-cassandra/bin/activate.fish

install_deps:
	pip install -r requirements.txt
